### ISSUE TITLE
**OK** Lib Message BaseOpenMessage

### ISSUE THREAD

**Issue by Gozilla01** [Gozilla01/openhab2-addons-Pre-New-Build#28]
Modificare in `BaseOpenMessage` la funzione `protected static String b` per gestire correttamente i comandi gruop.
Il `WHERE` con `Lighting.Type.GROUP` ha gia il prefisso #, nel `switch case` non è necessario aggiungere `#`
**Da:**
```
protected static String b(final String s, final Type type) {
        switch (BaseOpenMessage$1.a[type.ordinal()]) {
            case 1:
            case 2:
            case 4: {
                return s;
            }
            case 5: {
                return s.concat("#9");
            }
            case 3: {
                return "#".concat(s);
            }
            default: {
                throw new IllegalArgumentException("invalid type");
            }
        }
    }
```
**A:**
```
protected static String b(final String s, final Type type) {
        switch (BaseOpenMessage$1.a[type.ordinal()]) {
            case 1:
            case 2:
            case 3:
            case 4: {
                return s;
            }
            case 5: {
                return s.concat("#9");
            }
            default: {
                throw new IllegalArgumentException("invalid type");
            }
        }
    }
```

**Comment by Gozilla01** [comment]
Problemi con` lightingType` diverso da `POINT_TO_POINT`

```
2019-07-20 18:14:36.416 [DEBUG] [et.handler.OpenWebNetLightingHandler] - ==OWN:LightingHandler== toWhere(ChannelUID) ownId=1.#2#4#01
2019-07-20 18:14:36.419 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.openwebnet.handler.OpenWebNetLightingHandler@93e32a': invalid integer format
java.lang.IllegalArgumentException: invalid integer format
	at org.openwebnet.message.BaseOpenMessage.b(BaseOpenMessage.java:401) ~[?:?]
	at org.openwebnet.message.BaseOpenMessage.a(BaseOpenMessage.java:353) ~[?:?]
	at org.openwebnet.message.Lighting.requestTurnOn(Lighting.java:135) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetLightingHandler.handleSwitchCommand(OpenWebNetLightingHandler.java:149) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetLightingHandler.handleChannelCommand(OpenWebNetLightingHandler.java:126) ~[?:?]
	at org.openhab.binding.openwebnet.handler.OpenWebNetThingHandler.handleCommand(OpenWebNetThingHandler.java:123) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [137:org.openhab.core:2.5.0.201907171010]
	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [137:org.openhab.core:2.5.0.201907171010]
	at com.sun.proxy.$Proxy4827.handleCommand(Unknown Source) [?:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [188:org.openhab.core.thing:2.5.0.201907171012]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [188:org.openhab.core.thing:2.5.0.201907171012]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [137:org.openhab.core:2.5.0.201907171010]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [137:org.openhab.core:2.5.0.201907171010]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-07-20 18:14:46.203 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - ##gw-openwebnet-conn## sending MON keepalive ACK
2019-07-20 18:14:46.205 [DEBUG] [org.openwebnet.bus.MyHomeConnection ] - MON SENDING    ======>>>>>> *#*1##
```


Commentando `BaseOpenMessage.a(s, type);` l'errore è risolto.
Non so a cosa serve questo  
Da:
```
public static Lighting requestTurnOn(final String s, final Type type) {
        BaseOpenMessage.a(s, type);
        return new Lighting(String.format("*%d*%d*%s##", Lighting.h, 1, BaseOpenMessage.b(s, type)));
    }
```

A:
```
public static LightingExt requestTurnOn(final String s, final Type type) {
        // .replaceFirst("\\##", "\\#") Correzione provvisoria per la problematica nel group con doppio ##
        // BaseOpenMessage.a(s, type); Correzione provvisoria per eliminare l'errore 
        // BaseOpenMessage.a(s, type);
        return new LightingExt(
                String.format("*%d*%d*%s##", LightingExt.h, 1, BaseOpenMessage.b(s, type).replaceFirst("\\##", "\\#")));
    }
```
